package smtpclient

import (
	"context"
	"fmt"
	"strings"

	smtp "github.com/kiliant/go-smtp"
	"github.com/kiliant/go-smtp/internal/smtpwire"
)

// Mail begins a mail transaction with MAIL FROM (RFC 5321 §4.1.1.2). from is
// a reverse-path without angle brackets; an empty string sends the null
// reverse-path <> used for delivery-status messages. Source routes are
// accepted when supplied but are never generated by Client.
func (c *Client) Mail(ctx context.Context, from string, opts *smtp.MailOptions) error {
	if c == nil || c.conn == nil {
		return errNilClient
	}
	path, err := validatePath(from)
	if err != nil {
		return err
	}
	c.conn.opMu.Lock()
	defer c.conn.opMu.Unlock()
	args, err := c.mailArgs(path, opts)
	if err != nil {
		return err
	}
	reply, err := c.commandLocked(ctx, "MAIL", args, c.conn.mailTimeout, stateGreeted, stateTLS, stateAuthenticated)
	if err != nil {
		return err
	}
	if err := unexpectedReply("MAIL", reply, c.conn.enhancedStatusCodes(), 250); err != nil {
		return err
	}
	c.conn.mu.Lock()
	if c.conn.state != stateClosed {
		c.conn.transactionBase = c.conn.state
		c.conn.state = stateTransaction
		c.conn.recipients = nil
	}
	c.conn.mu.Unlock()
	return nil
}

func (c *Client) mailArgs(path string, opts *smtp.MailOptions) ([]string, error) {
	args := []string{"FROM:" + path}
	if opts == nil {
		return args, nil
	}
	params := make([]smtp.Param, 0, len(opts.Extra)+1)
	if opts.Auth != "" {
		params = append(params, smtp.Param{Keyword: "AUTH", Value: smtp.EncodeXtext(opts.Auth)})
	}
	params = append(params, opts.Extra...)
	encoded, err := c.encodeParams(params, opts.AllowUnadvertisedParameters)
	if err != nil {
		return nil, err
	}
	return append(args, encoded...), nil
}

func (c *Client) encodeParams(params []smtp.Param, allowUnadvertised bool) ([]string, error) {
	encoded := make([]string, 0, len(params))
	for _, param := range params {
		wireParam, err := smtpwire.EncodeParam(smtpwire.Param{Keyword: param.Keyword, Value: param.Value})
		if err != nil {
			return nil, fmt.Errorf("smtpclient: invalid esmtp parameter %q: %w", param.Keyword, err)
		}
		if required := parameterExtension(param); !allowUnadvertised && required != "" && !c.advertises(required) {
			return nil, fmt.Errorf("smtpclient: server did not advertise extension %q required by parameter %q", required, param.Keyword)
		}
		encoded = append(encoded, wireParam)
	}
	return encoded, nil
}

// parameterExtension maps the esmtp-parameters whose keyword differs from
// their advertising EHLO extension. Unknown parameters deliberately fall back
// to their own keyword: that preserves Extra as an open-ended escape hatch
// while still providing useful validation for registered parameter families.
func parameterExtension(param smtp.Param) string {
	switch strings.ToUpper(param.Keyword) {
	case "AUTH":
		return string(smtp.ExtAuth)
	case "RET", "ENVID", "NOTIFY", "ORCPT":
		return string(smtp.ExtDSN)
	case "BY":
		return string(smtp.ExtDeliverBy)
	case "HOLDFOR", "HOLDUNTIL":
		return string(smtp.ExtFutureRelease)
	case "SOLICIT":
		return string(smtp.ExtNoSoliciting)
	case "TRANSID":
		return string(smtp.ExtMTRK)
	case "BODY":
		switch strings.ToUpper(param.Value) {
		case "7BIT":
			return ""
		case "8BITMIME":
			return string(smtp.Ext8BitMIME)
		case "BINARYMIME":
			return string(smtp.ExtBinaryMIME)
		}
	}
	return strings.ToUpper(param.Keyword)
}

func (c *Client) advertises(keyword string) bool {
	c.conn.mu.Lock()
	defer c.conn.mu.Unlock()
	if strings.EqualFold(keyword, string(smtp.ExtAuth)) {
		_, ok := authAdvertisement(c.conn.ext)
		return ok
	}
	_, ok := c.conn.ext[strings.ToUpper(keyword)]
	return ok
}
