package smtpclient

import (
	"context"
	"fmt"
	"strings"

	smtp "github.com/kiliant/go-smtp"
	"github.com/kiliant/go-smtp/internal/smtpwire"
)

// Mail begins a mail transaction with MAIL FROM (RFC 5321 §4.1.1.2). from is
// a reverse-path without angle brackets; an empty string sends the null
// reverse-path <> used for delivery-status messages. Source routes are
// accepted when supplied but are never generated by Client.
func (c *Client) Mail(ctx context.Context, from string, opts *smtp.MailOptions) error {
	if c == nil || c.conn == nil {
		return errNilClient
	}
	path, err := validatePath(from)
	if err != nil {
		return err
	}
	c.conn.opMu.Lock()
	defer c.conn.opMu.Unlock()
	args, err := c.mailArgs(path, opts)
	if err != nil {
		return err
	}
	reply, err := c.commandLocked(ctx, "MAIL", args, c.conn.mailTimeout, stateGreeted, stateTLS, stateAuthenticated)
	if err != nil {
		return err
	}
	if err := unexpectedReply("MAIL", reply, c.conn.enhancedStatusCodes(), 250); err != nil {
		return err
	}
	c.conn.mu.Lock()
	if c.conn.state != stateClosed {
		c.conn.transactionBase = c.conn.state
		c.conn.state = stateTransaction
		c.conn.recipients = nil
	}
	c.conn.mu.Unlock()
	return nil
}

func (c *Client) mailArgs(path string, opts *smtp.MailOptions) ([]string, error) {
	args := []string{"FROM:" + path}
	if opts == nil {
		return args, nil
	}
	params := make([]smtp.Param, 0, len(opts.Extra)+1)
	if opts.Auth != "" {
		params = append(params, smtp.Param{Keyword: "AUTH", Value: smtp.EncodeXtext(opts.Auth)})
	}
	params = append(params, opts.Extra...)
	encoded, err := c.encodeParams(params, opts.AllowUnadvertisedParameters)
	if err != nil {
		return nil, err
	}
	return append(args, encoded...), nil
}

func (c *Client) encodeParams(params []smtp.Param, allowUnadvertised bool) ([]string, error) {
	encoded := make([]string, 0, len(params))
	for _, param := range params {
		wireParam, err := smtpwire.EncodeParam(smtpwire.Param{Keyword: param.Keyword, Value: param.Value})
		if err != nil {
			return nil, fmt.Errorf("smtpclient: invalid esmtp parameter %q: %w", param.Keyword, err)
		}
		if !allowUnadvertised && !c.advertises(param.Keyword) {
			return nil, fmt.Errorf("smtpclient: server did not advertise extension %q required by parameter", param.Keyword)
		}
		encoded = append(encoded, wireParam)
	}
	return encoded, nil
}

func (c *Client) advertises(keyword string) bool {
	c.conn.mu.Lock()
	defer c.conn.mu.Unlock()
	_, ok := c.conn.ext[strings.ToUpper(keyword)]
	return ok
}
